--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 16.06.2019 22:54:28
-- Server version: 5.5.5-10.1.38-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE database2;

--
-- Drop table `calculation`
--
DROP TABLE IF EXISTS calculation;

--
-- Drop table `client`
--
DROP TABLE IF EXISTS client;

--
-- Drop table `price`
--
DROP TABLE IF EXISTS price;

--
-- Set default database
--
USE database2;

--
-- Create table `price`
--
CREATE TABLE price (
  param_id INT(11) NOT NULL AUTO_INCREMENT,
  param_name VARCHAR(255) DEFAULT NULL,
  measure VARCHAR(255) DEFAULT NULL,
  price DECIMAL(19, 2) DEFAULT NULL,
  PRIMARY KEY (param_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `client`
--
CREATE TABLE client (
  clinet_id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (clinet_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 43,
AVG_ROW_LENGTH = 2048,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `calculation`
--
CREATE TABLE calculation (
  calc_id INT(11) NOT NULL AUTO_INCREMENT,
  client_id INT(11) DEFAULT NULL,
  param_id INT(11) DEFAULT NULL,
  value INT(11) DEFAULT NULL,
  PRIMARY KEY (calc_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE calculation 
  ADD CONSTRAINT FK_calculation_client_clinet_id FOREIGN KEY (client_id)
    REFERENCES client(clinet_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE calculation 
  ADD CONSTRAINT FK_calculation_price_param_id FOREIGN KEY (param_id)
    REFERENCES price(param_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- 
-- Dumping data for table price
--
INSERT INTO price VALUES
(1, 'time', 'minutes', 3.00),
(2, 'distance', 'km', 50.00);

-- 
-- Dumping data for table client
--
INSERT INTO client VALUES
(33, '456', '987'),
(34, '456', '987'),
(35, '489', '456'),
(36, '489', '456'),
(37, 'jkll', '78'),
(38, 'jkll', '78'),
(39, 'dghj', '8'),
(40, 'luba', '456789'),
(41, 'miisha', '123456789'),
(42, 'luba', '1234568');

-- 
-- Dumping data for table calculation
--
INSERT INTO calculation VALUES
(1, 39, 2, 30),
(2, 40, 2, 50),
(3, 41, 1, 90),
(4, 42, 1, 50);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;